apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-v1
  namespace: default
  labels:
    app: deployment-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-golang
  template:
    metadata:
      labels:
        app: deployment-golang
    spec:
      containers:
      - name: go-service
        image: grc.io/impressive-mile-343315/go-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service-golang
  namespace: default
spec:
  selector:
    app: deployment-golang
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 8080