version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: clone code
          command: git clone https://github.com/smart-think-app/golang-service.git 
      - run:
          name: build docker
          command:  |
            cp Dockerfile /golang-service
            cd golang-service && docker build --tag tqhuy1996developer/go-dk1 .
      # - run:
      #     name: Run tests
      #     command: go test -v