version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: clone code and build docker
          command: docker build https://github.com/smart-think-app/golang-service
      # - run:
      #     name: Run tests
      #     command: go test -v